### ISSUE TITLE
Can't delete event from year view mode.

### ISSUE THREAD

**Issue by drumset** [DHTMLX/scheduler-howto-dotnet-core#1] opened 2019-06-01 09:57 UTC
I can  create and edit from year view mode but isn't posible delete. No request in DeleteEvent api method.
How can I do it?

Thanks in advance!

**Comment by AlexKlimenkov** [comment] 2019-06-27 12:13
Hi,
it was probably a bug in one of the recent builds and it seems to be fixed now.
I've just checked the latest package and wasn't unable to reproduce the issue.

If you're still facing this error - please reopen and specify the exact version of the scheduler you use, v5.2.1 is the latest one.

Best,

**Closed as completed by AlexKlimenkov** 2019-06-27 12:13 UTC
